# Generated by Django 5.1.4 on 2025-01-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_alter_bb_options_alter_bb_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Bb_images/', verbose_name='Изображение'),
        ),
    ]
