# Generated by Django 5.1.4 on 2025-01-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_customuser_is_staff_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
    ]
